---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This Python component publishes the given message over MQTT every second."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "Hello from Python!"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "com.example.PythonMqttHello:mqttproxy:1":
          policyDescription: "Allows access to publish to all topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/python-mqtt-hello.zip"
        Unarchive: ZIP
Lifecycle:
  Install: |
    echo "Lifecycle::::: :::::::: INSTALL"
    # Fetch the current username
    USERNAME=$(whoami)
    echo "Current username: $USERNAME"

    # Create the virtual environment in the user's home directory
    ENV_DIR="/home/$USERNAME/.local/.greengrass-env"
    if [ ! -d "$ENV_DIR" ]; then
      echo "Creating virtual environment at $ENV_DIR"
      python3 -m venv "$ENV_DIR"
    else
      echo "Virtual environment already exists at $ENV_DIR skipping"
    fi

    # Upgrade pip and install dependencies
    echo "Upgrading pip in the virtual environment"
    "$ENV_DIR/bin/pip" install --upgrade pip

    echo "Installing dependencies from requirements.txt"
    "$ENV_DIR/bin/pip" install -r {artifacts:decompressedPath}/python-mqtt-hello/requirements.txt
  Run: |
    echo "Lifecycle::::: :::::::: RUN"
    # Fetch the current username
    USERNAME=$(whoami)
    echo "Current username: $USERNAME"

    # Activate the virtual environment and run the script
    ENV_DIR="/home/$USERNAME/.local/.greengrass-env"
    echo "Activating virtual environment from $ENV_DIR"
    source "$ENV_DIR/bin/activate"

    echo "Running main.py script"
    # python3 -u {artifacts:decompressedPath}/python-mqtt-hello/main.py "{configuration:/Message}"
    "$ENV_DIR/bin/python3" -u {artifacts:decompressedPath}/python-mqtt-hello/main.py "{configuration:/Message}"
