---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This Python component publishes the given message over MQTT every second."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "Hello from Python!"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "com.example.PythonMqttHello:mqttproxy:1":
          policyDescription: "Allows access to publish to all topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/python-mqtt-hello.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: |
        if [ ! -d "/greengrass-env" ]; then
          python3 -m venv /greengrass-env
        fi
        /greengrass-env/bin/pip install --upgrade pip
        /greengrass-env/bin/pip install -r {artifacts:decompressedPath}/python-mqtt-hello/requirements.txt
      Run: |
        source /greengrass-env/bin/activate
        python3 -u {artifacts:decompressedPath}/python-mqtt-hello/main.py "{configuration:/Message}"
